
/** Inscriptions de minuit à 13h, éliminations de 13h30 à 21h */
export const AVALANCHE_REGISTRATION_END_HOUR = 13;
export const AVALANCHE_ELIMINATION_START_HOUR = 13.5;
export const AVALANCHE_ELIMINATION_END_HOUR = 21;

export const AVALANCHE_NUMBER_MIN = 1;
export const AVALANCHE_NUMBER_MAX = 50;

export const AVALANCHE_MIN_PLAYERS = 2;

export const AVALANCHE_REWARD = {
  money: 750,
  xp: 600,
  expeditions: 4,
};

export const AVALANCHE_PARTICIPATION_FRAGMENTS = 5;

export const AVALANCHE_ACCENT_COLOR = 0x8ecae6;
export const AVALANCHE_FINISHED_ACCENT_COLOR = 0x57cc99;

/** Raisons d'élimination tirées au hasard — suivent la mention du joueur */
export const AVALANCHE_DEATHS = [
  'a voulu prendre un selfie avec le yéti',
  's\'est arrêté pour refaire ses lacets',
  'a crié trop fort en voyant une marmotte',
  'a confondu la piste noire avec le buffet',
  'a tenté de descendre en luge sur son sac à dos',
  'a oublié ses crampons au chalet',
  'a voulu tester si la neige était bien fraîche',
  'a répondu au téléphone en pleine montée',
  'a suivi un panneau « raccourci » écrit à la main',
  'a fait une sieste sur la corniche',
  'a partagé son sandwich avec un chamois vexé',
  's\'est fait doubler par sa propre écharpe',
  'a voulu planter un drapeau au mauvais endroit',
  'a éternué un peu trop fort',
  'a lancé une boule de neige sur le sommet',
  'a voulu filmer l\'avalanche en mode paysage',
  'a pris la mauvaise télécabine',
  's\'est arrêté pour admirer le panorama',
  'a mis ses skis à l\'envers',
  'a chanté du Céline Dion dans le couloir d\'avalanche',
  'a voulu vérifier si l\'écho fonctionnait',
  'a trébuché sur un caillou nommé Gérard',
  'a voulu escalader sans les mains, pour la photo',
  'a cru que la neige était en sucre glace',
  'a voulu faire un TikTok au bord du précipice',
  'a lâché son bâton pour applaudir',
  's\'est endormi dans le télésiège',
  'a voulu caresser un bouquetin',
  'a mis de la musique à fond dans ses écouteurs',
  'a cru entendre le camion à pizza',
  'a voulu descendre à reculons pour impressionner',
  'a oublié de fermer sa combinaison',
  'a glissé sur une peau de banane, en montagne, on ne sait pas comment',
  'a voulu construire un igloo en pleine coulée',
  's\'est arrêté pour compter les flocons',
  'a discuté météo avec un randonneur trop bavard',
  'a voulu tester son nouveau drone',
  'a confondu le nord et le sud',
  'a suivi les traces d\'un autre joueur, qui était déjà mort',
  'a voulu faire un bonhomme de neige à taille réelle',
  'a cherché du réseau pour poster sa story',
  'a voulu boire un chocolat chaud au sommet',
  's\'est pris les pieds dans sa propre corde',
  'a oublié que la montagne, ça glisse',
  'a voulu doubler par la gauche',
  'a crié « ça passe » juste avant que ça ne passe pas',
  'a voulu ranger son sac au pire moment',
  'a fait confiance à la météo',
  'a voulu escalader en tongs',
  'a pris une pause clope à 3000 m',
  'a suivi un GPS qui datait de 1998',
  'a voulu offrir une noisette à un écureuil armé',
  'a trop regardé en bas',
  'a voulu vérifier la solidité de la corniche, en sautant dessus',
  'a laissé tomber ses clés dans la crevasse et est allé les chercher',
  'a fait demi-tour pour récupérer son bonnet',
  'a voulu refaire la scène de Titanic sur un rocher',
  'a parié qu\'il tiendrait plus longtemps que les autres',
  'a été trahi par ses chaussures de ville',
  'a voulu tester la luge en position debout',
  'a cru que le grondement venait de son ventre',
  'a demandé son chemin à une marmotte',
  'a voulu faire la course avec l\'avalanche',
  's\'est arrêté pour aider un touriste, quelle erreur',
  'a voulu prouver qu\'il n\'avait pas froid',
  'a enlevé son casque pour la photo',
  'a voulu planter sa tente sur une pente à 45°',
  'a confondu les crampons et les chaussons',
  'a voulu tester l\'écho avec un cri de Tarzan',
  'a fait tomber son thermos et l\'a poursuivi',
  'a voulu faire une pause tactique au mauvais endroit',
  'a cru qu\'il était hors de portée',
  'a écouté les conseils d\'un inconnu au chalet',
  'a voulu dépasser sa zone de confort, littéralement',
  'a oublié de regarder derrière lui',
  'a voulu ajuster son écharpe en pleine bourrasque',
  'a pris la dernière part de tartiflette et le karma a répondu',
  'a voulu gratter un ticket de loto sur la pente',
  'a cru que « avalanche » était une métaphore',
  'a fait une story « tout va bien » trente secondes trop tôt',
  'a voulu tester si la neige rebondit',
  'a voulu prendre le raccourci de l\'année dernière',
  'a été déconcentré par un saint-bernard trop mignon',
  'a voulu se reposer « juste deux minutes »',
  'a fait un pari stupide avec son binôme',
  'a voulu changer de position au dernier moment',
  'a suivi un flocon des yeux un peu trop longtemps',
  'a voulu inaugurer sa nouvelle doudoune',
  'a cru que le silence était bon signe',
  'a voulu faire un angle mort en snowboard',
  'a fait tomber son portable et a plongé',
  'a voulu vérifier son classement pendant la coulée',
  'a demandé un selfie au bot',
  'a voulu couper à travers le hors-piste',
  'a mis trop longtemps à choisir sa playlist',
  'a confondu la poudreuse et le matelas',
  'a voulu faire un backflip pour les fans',
  'a oublié que la gravité existe aussi ici',
  'a voulu négocier avec la montagne',
  'a cru qu\'il avait un joker',
  'a voulu tester son ARVA, sans ARVA',
  'a suivi le mauvais groupe de randonneurs',
  'a voulu faire le malin sur la crête',
  'a été distrait par une vache égarée',
  'a voulu chausser ses skis à l\'envers de la pente',
  'a fait une pause photo panoramique à 360°',
  'a voulu rattraper son gant emporté par le vent',
  'a cru que le refuge était juste là',
  'a voulu doubler l\'avalanche par la droite',
  'a répondu « deux secondes » à l\'avertissement',
  'a voulu tester la résistance du manteau neigeux, avec un talon',
  'a lancé un « regardez ça ! » jamais terminé',
  'a voulu traverser la plaque à vent en dansant',
  'a fait confiance à un raccourci Google Maps',
  'a voulu emporter un souvenir du sommet, trop lourd',
  'a cru entendre son nom dans le vent',
  'a voulu régler ses lunettes en plein virage',
  'a été emporté par son propre enthousiasme',
  'a voulu faire une dernière tentative de record',
  'a cherché ses lunettes qu\'il avait sur le front',
  'a voulu s\'entraîner au cri de guerre',
  'a pris une décision audacieuse, et fausse',
  'a voulu tester le hors-piste « juste un peu »',
  'a été trahi par un lacet défait',
  'a voulu mettre de la crème solaire pendant la coulée',
  'a cru que rester immobile suffirait',
  'a voulu lancer un drapeau de trêve à la montagne',
  'a fait un high-five qui a tout déclenché',
  'a voulu écouter le silence de la montagne, dernière écoute',
  'a confondu son sac de couchage avec un airbag',
  'a voulu raconter une blague, la chute était ailleurs',
  'a insisté pour porter le sac le plus lourd',
  'a voulu descendre en rappel sans corde',
  'a oublié que les autres aussi visaient la victoire',
  'a voulu profiter du paysage une dernière fois, et ce fut vrai',
];
